version: "3.9"

services:
  postgres_database:
    image: postgres:latest
    container_name: postgres_database
    env_file:
      - "../.env"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DATABASE_PORT}:5432
    environment:
      - POSTGRES_DATABASE_NAME=${POSTGRES_DATABASE_NAME}
      - POSTGRES_DATABASE_USER=${POSTGRES_DATABASE_USER}
      - POSTGRES_DATABASE_PASSWORD=${POSTGRES_DATABASE_PASSWORD}
      - POSTGRES_DATABASE_PORT=${POSTGRES_DATABASE_PORT}
    restart: always
    networks:
      - sample-network

  pgadmin_ui:
    image: dpage/pgadmin4:8.7
    container_name: pgadmin-ui
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ACCOUNT}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - sample-network

networks:
  sample-network:
    name: sample-network

volumes:
  postgres-db-data:


