version: "3.9"

services:
  postgres_database:
    image: postgres:16-alpine
    container_name: postgres_database
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_DATABASE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
    restart: always
    networks:
      - sample-network

  pgadmin_ui:
    image: dpage/pgadmin4
    container_name: pgadmin-ui
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ACCOUNT}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - sample-network

networks:
  sample-network:
    name: sample-network

volumes:
  postgres-db-data:


